name:   'Mark Borg'
url:    'https://mark-borg.github.io/'
author: 'Mark Borg'

gems: [jekyll-paginate]

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
timezone: 'Europe/Malta'
highlighter: 'rouge'
