name:   'Mark Borg - my blog'
url:    'https://mark-borg.github.io/'
author: 'Mark Borg'
description: 'A blog on computer vision, AI, machine learning, and data science'

gems: [jekyll-paginate]

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
timezone: 'Europe/Malta'
highlighter: 'rouge'

plugins:
  - jekyll-feed
